version: '3'
services:
  mysql:
    image: docker.io/mysql
    ports:
      - 3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sakila
      MYSQL_DATABASE: sakila
      MYSQL_USERNAME: sakila
      MYSQL_PASSWORD: sakila

